# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2018-08-02 20:49
from __future__ import unicode_literals

from django.db import migrations, models
import mediablogapp.models


class Migration(migrations.Migration):

    dependencies = [
        ('mediablogapp', '0002_article'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='image',
            field=models.ImageField(upload_to=mediablogapp.models.generate_filename),
        ),
        migrations.AlterField(
            model_name='article',
            name='title',
            field=models.CharField(max_length=1000),
        ),
    ]
