# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2018-08-02 22:59
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mediablogapp', '0003_auto_20180802_2349'),
    ]

    operations = [
        migrations.CreateModel(
            name='MyArticles',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
            },
            bases=('mediablogapp.article',),
        ),
    ]
