# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2018-08-03 09:57
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mediablogapp', '0004_myarticles'),
    ]

    operations = [
        migrations.DeleteModel(
            name='MyArticles',
        ),
    ]
