# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2018-08-04 16:07
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('mediablogapp', '0007_auto_20180804_0254'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='users_reaction',
            field=models.ManyToManyField(blank=True, to=settings.AUTH_USER_MODEL),
        ),
    ]
