# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2018-08-04 17:05
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mediablogapp', '0009_useraccount'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comment',
            options={},
        ),
    ]
